[tool.poetry]
name = "promplate"
version = "0.1.0"
description = "cross-language prompt engineering framework"
authors = ["Muspi Merol <admin@muspimerol.site>"]
license = "MIT"
readme = "../README.md"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
